### ISSUE TITLE
Autenticación

### ISSUE THREAD

**Issue by jonmartinez** [mouneyrac/moodle-auth_googleoauth2#150]
Antes que nada dar las gracias por este maravilloso plugin ha facilitado mucho nuestro proceso de registro en moodle, pero me interesa mucho la opción de que cuando un usuario desee salir de moodle también lo haga en las cuentas de google, esto debido a que cuendo un usuario se autentica en moodle con oAuth2 inicia sesión automáticamente en cuentas de google.
Agradezco si tienen una solución a este inconveniente.

**Comment by mouneyrac** [comment]
Google translate says:

"First of all thank you for this wonderful plugin has greatly facilitated our process of registration in moodle, but I really want the option that when a user wishes to leave moodle also do it in the accounts of google, this because cuendo one moodle user authenticates with OAuth2 automatically logs in google accounts. 
I appreciate if they have a solution to this problem."

**Comment by mouneyrac** [comment]
this is the same issue as https://github.com/mouneyrac/moodle-auth_googleoauth2/issues/109, closing (thanks for the report)
