### ISSUE TITLE
Error con Google

### ISSUE THREAD

**Issue by edgduran** [mouneyrac/moodle-auth_googleoauth2#193]
Since update the plugin to the latest version , an error vializar after authenticating with the Google account , no error on the part of Google because it's the same as I worked in the previous version to update.
The message that appears is this:

Internal Server Error

The Server Encountered an internal error or misconfiguration and was unable to complete your request .

Please contact the server administrator, webmaster@enlinea.ccpm.edu.mx and inform them of the time the error occurred , and anything you Might Have done that May Have Caused the error.

More information about this bug May be available in the server error log.

Additionally , a 500 Internal Server Error Error was Encountered while trying to use an ErrorDocument to handle the request .

Please, help me, What happens

**Comment by Stuboter** [comment]
Hello, I am having the exact same issue. The plugin is 100% freshly installed, I have followed all the steps, but I suspect Google has changed something, or Moodle 3.0 has broken something.

We have been running Moodle 3.0 for about a month, with no issues, and suddenly a few days ago our entire OAuth authentication through Google has stopped.

error_log in the root dir of the plugin says:

Default exception handler: auth_googleoauth2/google_failure Debug: 
Error code: google_failure

$a contents: 
* line 64 of /auth/googleoauth2/lib.php: moodle_exception thrown
* line 19 of /auth/googleoauth2/google_redirect.php: call to googleoauth2_provider_redirect()

I have spent several hours trying to debug this but to no avail.

Please help?

**Comment by shwetavagarwal** [comment]
We faced the same issue with a fresh install of Moodle 3.0.3 and the Oauth2 Plugin. It was fixed by changing default authentication method for users to "Oauth2".

**Comment by mouneyrac** [comment]
Tested on Moodle 3.1, Google still works perfectly on fresh install.

I checked Stuboter report and it is pretty weird, basically the plugin code says that the error is triggered because Google does not send the code in the redirect_url... very weird... Did the error disappear (maybe it was a Google issue)?

**Comment by Stuboter** [comment]
mouneyrac, thanks for your response.

So I literally was looking at this for *days* because it was stopping all of our students for our entire college from logging in. Ended up outsourcing it a fellow coder who looked at your plugin for a few hours ... No progress.

We were just about to implement a whole shift of authenticate college wide when it suddenly started working again!!!

A few days later, our server hosting company issued an update saying they changed something, broke some functionality to do with php, and fixed it when it became apparent. It didn't click on my end that it could possibly have been an unintentional break from our hosting company.

So if anyone else has this issue in the future, and if you're sure you've done a fresh install and set up Google correctly, then I would contact your hosting company asap and let them know.

**Comment by mouneyrac** [comment]
this is very interesting. Do you have the detail about the server PHP problem? It would be great to know which PHP settings is required by the plugin (but apparently not so much by Moodle if it was working.. or maybe it was breaking Moodle auth system? anyway it would be good to know what PHP settings cause the issue)

**Comment by Stuboter** [comment]
I unfortunately can't help you there. I never followed it up that closely, and I'm sure it's been lost in time now.

Moodle manual authentication was still working, but from what I could gather, your plugin couldn't recognise what was being returned by Google.

Our hosting company said this was a bug, though, not an innocent setting that could possibly have been okay in some circumstances. I can only assume other groups were having issues with their sites and brought it up with them. I don't think you need to pursue this :) I have since upgraded to 3.1 and it's been running great.

**Comment by mouneyrac** [comment]
Thanks for coming back explaining about the issue Stuboter. It will be very useful next time someone report this error, we will try to identify the exact cause then. Actually it reminds me that someone mentioned the plugin required a specific PHP setting but I can not find this post/issue anymore. But anyway, if you use the recommended Moodle PHP setting (https://docs.moodle.org/31/en/PHP#PHP_Settings) you should be fine anyway as I develop with the recommended PHP settings. 

I'll close this issue. Thanks to everyone for participating.
cheers,
Jerome
