### ISSUE TITLE
[Moodle 2.1] Oauth2 - facebook login is not working

### ISSUE THREAD

**Issue by sierratec** [mouneyrac/moodle-auth_googleoauth2#209]
Hi

We are using moodle 2.1 with Oauth2 plugin. Currently gmail authentication is working fine. We could able to login using gmail account. But when we try to login using facebook account below error occurs. The online link is www.sierratec.com/e-Test. Kindly suggest how to clear this. Thanks

Error
Your email address is not verified by the authentication method you selected. You likely have forgotten to click on a "verify email address" link that Google or Facebook should have sent you during your subscribtion to their service

**Comment by mouneyrac** [comment]
Hi sierratec,
Moodle 2.1 is not supported anymore by HQ since 2012: https://docs.moodle.org/dev/Releases
It is likely that no-one will fix this problem. Maybe have a try to the alternative I listed on https://moodle.org/plugins/view.php?id=40. Let us know if you find an alternative working with Facebook on 2.1, it would maybe interest other people.

I am closing this issue, anyone having a solution, feel free to still comment on this issue (it is possible even closed).

Cheers,
Jerome
